/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as DiscagemRouteImport } from './routes/discagem'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AgenteRouteImport } from './routes/agente'
import { Route as IndexRouteImport } from './routes/index'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscagemRoute = DiscagemRouteImport.update({
  id: '/discagem',
  path: '/discagem',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenteRoute = AgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/discagem': typeof DiscagemRoute
  '/leads': typeof LeadsRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/discagem': typeof DiscagemRoute
  '/leads': typeof LeadsRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/discagem': typeof DiscagemRoute
  '/leads': typeof LeadsRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agente'
    | '/configuracoes'
    | '/discagem'
    | '/leads'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agente'
    | '/configuracoes'
    | '/discagem'
    | '/leads'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/agente'
    | '/configuracoes'
    | '/discagem'
    | '/leads'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenteRoute: typeof AgenteRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DiscagemRoute: typeof DiscagemRoute
  LeadsRoute: typeof LeadsRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discagem': {
      id: '/discagem'
      path: '/discagem'
      fullPath: '/discagem'
      preLoaderRoute: typeof DiscagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agente': {
      id: '/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenteRoute: AgenteRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DiscagemRoute: DiscagemRoute,
  LeadsRoute: LeadsRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
